
cat:
	cat Makefile


serve:
	(export BOKEH_ALLOW_WS_ORIGIN=10.12.68.5:8889 && panel serve --show --port 8889 1_geojson-viewer-panel.ipynb)



serve-80:
	(export BOKEH_ALLOW_WS_ORIGIN=10.12.68.5:80 && sudo panel serve --show --port 80 3_AWS_S3_COST_APP_Cloud_Class_Demo.ipynb)
