FROM tbutzer/panel-hv

ENV BOKEH_ALLOW_WS_ORIGIN=10.12.69.188,localhost

ENV CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

RUN pip install panel && pip install hvplot && pip install xarray \
    && pip install rasterio==1.1.8 \
    && pip install datashader

COPY view.ipynb /home/view.ipynb

WORKDIR /home

CMD panel serve --address 0.0.0.0 --prefix=/view/ view.ipynb 

