FROM python


RUN pip3 install --upgrade pip \
    && pip3 install jupyter \
    && pip3 install boto3 \
    && pip3 install matplotlib \
    && pip3 install requests \
    && pip3 install pandas \
    && pip3 install seaborn \
    && pip3 install plotly \
    && pip3 install xlrd  \
    && pip3 install panel


WORKDIR /home
